### ISSUE TITLE
Broken package links

### ISSUE THREAD

**Issue by dcampbell24** [kerinin/cfrp-rs#1]
The [homepage link](http://kerinin.github.io/cfrp-rs) is returning a 404 right now and I think the repository page, which is currently pointing to the same location, should point to https://github.com/kerinin/cfrp-rs instead.

If you don't have any content for a homepage right now, I would suggest removing that field from the package as I don't think it gives a good impression to other people when a project links to pages that don't exist.

**Comment by kerinin** [comment]
Good point, updating crate.
